import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CounterStoreProvider } from "@/providers/counter-store-provider";
import Header from "@/components/header";
import { AuthStoreProvider } from "@/providers/auth-store-provider";
import { LoginModel } from "@/components/login-model";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthStoreProvider>
          <Header />
          {children}
          <LoginModel />
        </AuthStoreProvider>
      </body>
    </html>
  );
}
